### PR TITLE
added console placeholder icons

### PR DESCRIPTION
**Pull request by mennenia**
Graphics for [this issue](https://github.com/CocoaPods/CocoaPods-app/issues/182#issuecomment-171461442)

New sketch file that has the ideas and context of the icons, as well as a separate page with all icons in artboards + selected states.

Preview:

podfile_exists

### CODE REVIEW

**Comment by mennenia** [comment]
@orta should I tag you in these PRs btw, or do you see them anyway?

**Comment by orta** [comment]
I see every PR to all CocoaPods repos - so don't worry there

**Comment by orta** [comment]
Cool, gonna give it a second before merging: re the colour palette

**Comment by mennenia** [comment]
Sorted

**Comment by orta** [comment]
ace

**Pull request merged**
